name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        git config user.name "Bini Bot"
        git config user.email "vinikappke@gmail.com"
        git fetch
        git checkout master
        npx webpack --mode production -o ./dist
        git add dist
        git commit -m "Update build files"
        git push
